### ISSUE TITLE
下载管理功能异常

### ISSUE THREAD

**Issue by 1216338727aa** [UbuntuKylin/ubuntu-kylin-software-center#12]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200313-amd64.iso
测试环境：联想启天M415-N000台式机
测试步骤：
1.麒麟软件商店-安装一个软件
2.点击下载管理，

预期结果：下载管理界面功能正常
实际结果：打开麒麟软件，直接查看下载管理，鼠标放在【X】和【清空已下载】都有高亮提示，鼠标点击下载管理空白处无反应，安装完成一个软件后发现以下几个问题：1.鼠标放在【X】【清空已下载】无高亮或者显示不全 2,点击【X】不会关闭  3.点击【清空已下载】不会清空下载列表 4.概率点击【X】不会关闭下载管理 5.点击【清空已下载】概率关闭下载管理  6.可以点击点击下载管理后面的界面  7.下载完成多软件，下载管理界面会有一个申拉条，鼠标点击移动和鼠标滚轮都无反应。

**Comment by wenbo607** [comment]
kwin引起的问题，已经修复

**Comment by 1216338727aa** [comment]
20200521 test paaed
