### ISSUE TITLE
启动动画的优化

### ISSUE THREAD

**Issue by moshengrenzenme** [UbuntuKylin/ubuntu-kylin-software-center#3]
现在的启动代码是通过播放一张GIF图片的，但是受限于GIF图片的限制，分辨率不能做到太高，在高分辨率的屏幕上更是如此，我在注释的代码里看到了一段和我之前思路一样的代码，就是把启动代码切图成一个个的小图片，然后播放，这样话不会受限于分辨率的限制，但是对应的性能问题不清楚，不过如果性能损耗在可以接受的范围内感觉可以试试，具体文件是ui/loadingdiv.py里，看看能不能接受性能损失，这个启动动画思路也是现在安卓的loading思路

**Comment by wenbo607** [comment]
这个问题衡量过，以前用的这种方式，就是被注释的代码，由于飞腾1500的性能过低，在上面的效果不佳，才切换成目前方式，当然也可根据运行环境来判断运行哪种开机动画程序，已记录，下次版本开发前会加入到讨论问题中

**Comment by wenbo607** [comment]
已使用新的启动动画，采用图片播放方式。

**Comment by 1216338727aa** [comment]
20200521 test passed
