### ISSUE TITLE
关于“到底要不要在安装包里放大量icon和其它资源”的讨论

### ISSUE THREAD

**Issue by moshengrenzenme** [UbuntuKylin/ubuntu-kylin-software-center#8]
软件包里包含大量的icon和其他的资源，比如说数据库等，会造成软件包越来越大，能不能只带一小部分的必要文件，比如首页的一部分软件的icon，其他的可以在需要的时候联网下载，包括评论分值等，这样可以减小体积，并且可以按需更新，不用担心一次性下载大量的东西对服务器完成很大的压力，数据库也可以根据不同的机器进行测试如果性能足够的话，完全可以用sql文件代替，第一次运行的时候建立数据库，然后进行正常更新。服务器端只要做好对应的API开发就可以把压力从连接少流量大改成小流量多连接，还可以使用缓存把服务器的数据库压力减到最低，包括推荐软件列表的分值也可以是服务器用定时任务计算。当然也有考虑到不联网的时候，既然不联网了，那么一般情况下都是知道自己装的软件是什么的，评论也好，图标也好就可以变得无所谓，这个时候商店更多的是作为一个图形界面的安装器，所以在不联网的时候也显示icon和评论什么的会造成一种作假的感觉，也可以说不联网显示评论和icon是个伪命题，包括评论审核什么的可以开放一个接口让社区组的大家帮忙审核，也可以做到及时更新，减轻开发人员压力

**Comment by wenbo607** [comment]
icon和截图打进deb包，是因为软件商店不仅用于社区也用于商业，商业很多项目是无网络环境的，不将icon和截图等资源带入会很丑。

**Comment by wenbo607** [comment]
超清软件截图使用的是资源服务器上下载，采用的策略是，有先查找下载的缓存目录，其次从资源服务器下载，以上都没有，最后才是使用本地包中自带的非高清图。
